### ISSUE TITLE
Cannot get it to install on macos 10.15.7 (19H2026)

### ISSUE THREAD

**Issue by fugueink** [dracula/libreoffice#15] opened 2023-04-06 17:47 UTC
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.

I'm sorry, I can't do that.

I am not good at using the Terminal. I drag and drop things into the Terminal, which gives the whole heirarchy of my hard drive. It would be very easy for anyone to hack my system.

I offer as much as is safe:

```
</libreoffice-master>  % <my user folder>/Library/Application\ Support/LibreOffice/4/user/config/libreoffice-master/install.sh
Copying palette to config directory ...
cp: directory <my user folder>/.config/libreoffice/*/user/config does not exist
Running add-dracula-application-colors.sh ...
./add-dracula-application-colors.sh: line 7: Support/LibreOffice/*/user/registrymodifications.xcu: No such file or directory
./add-dracula-application-colors.sh: line 14: realpath: command not found
cp: : No such file or directory
Settings file doesn't exist in expected location. Aborting ...
```

Have I missed anything you need to know?

Thank you!

K

**Comment by eleanor-clifford** [comment] 2023-04-06 18:35
duplicate of #11, which I might have just fixed, but I can't test as I don't have a macOS system.

**Closed as completed by eleanor-clifford** 2023-04-06 18:35 UTC
